import { Booking } from "./Booking"
import { Store } from "./Store"

export enum ProductType {
  ART_SUPPLIES = "ART_SUPPLIES",
  AUTOMOTIVE_PARTS = "AUTOMOTIVE_PARTS",
  BEVERAGE = "BEVERAGE",
  BIKE = "BIKE",
  BOATS = "BOATS",
  BOOKS = "BOOKS",
  CAR = "CAR",
  CLOTHING = "CLOTHING",
  CONSTRUCTION_MATERIALS = "CONSTRUCTION_MATERIALS",
  COSMETICS = "COSMETICS",
  ELECTRONICS = "ELECTRONICS",
  FOOD = "FOOD",
  FURNITURE = "FURNITURE",
  GAMING_HARDWARE = "GAMING_HARDWARE",
  GARDENING_TOOLS = "GARDENING_TOOLS",
  HOME_APPLIANCES = "HOME_APPLIANCES",
  INDUSTRIAL_EQUIPMENT = "INDUSTRIAL_EQUIPMENT",
  JEWELRY = "JEWELRY",
  MOBILE_DEVICES = "MOBILE_DEVICES",
  MUSICAL_INSTRUMENTS = "MUSICAL_INSTRUMENTS",
  OFFICE_SUPPLIES = "OFFICE_SUPPLIES",
  PET_SUPPLIES = "PET_SUPPLIES",
  PHARMACEUTICALS = "PHARMACEUTICALS",
  PHOTOGRAPHY_EQUIPMENT = "PHOTOGRAPHY_EQUIPMENT",
  AVIATION = "AVIATION",
  SOFTWARE = "SOFTWARE",
  SPORTS_EQUIPMENT = "SPORTS_EQUIPMENT",
  TEXTILES = "TEXTILES",
  TOYS = "TOYS",
}

export interface Product {
  id: string
  createdAt: Date
  updatedAt: Date
  name: string
  type: ProductType
  store: Store
  storeId: string
  bookings: Booking[]
}
