import { Booking } from "./Booking"
import { User } from "./User"

export enum ServiceType {
  ACCOUNTING = "ACCOUNTING",
  BEAUTY_SERVICES = "BEAUTY_SERVICES",
  CATERING = "CATERING",
  CLEANING = "CLEANING",
  CONSULTING = "CONSULTING",
  COUNSELING = "COUNSELING",
  DELIVERY = "DELIVERY",
  DJ = "DJ",
  EVENT_PLANNING = "EVENT_PLANNING",
  FINANCIAL_PLANNING = "FINANCIAL_PLANNING",
  GRAPHIC_DESIGN = "GRAPHIC_DESIGN",
  INTERIOR_DESIGN = "INTERIOR_DESIGN",
  LANDSCAPING = "LANDSCAPING",
  LEGAL_ADVICE = "LEGAL_ADVICE",
  MARKETING = "MARKETING",
  MEDICAL_SERVICES = "MEDICAL_SERVICES",
  PERSONAL_TRAINING = "PERSONAL_TRAINING",
  PET_CARE = "PET_CARE",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  REAL_ESTATE = "REAL_ESTATE",
  REPAIRS = "REPAIRS",
  SECURITY = "SECURITY",
  SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT",
  TRANSPORT = "TRANSPORT",
  TRAVEL_PLANNING = "TRAVEL_PLANNING",
  TUTORING = "TUTORING",
  VENUE_RENTAL = "VENUE_RENTAL",
  WEB_DEVELOPMENT = "WEB_DEVELOPMENT",
}

export interface Service {
  id: string
  name: string
  type: ServiceType
  owner: User
  ownerId: string
  bookings: Booking[]
}
